---
title: "S&P 500_BLS"
author: "JP"
date: "11/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
warning = F
message = F
pacman::p_load(
  stringr,
  plyr,
  reshape2,
  tidyverse,
  lubridate,
  tidyr,
  forecast,
  rvest,
  tidyquant,
  janitor,
  quantmod,
  fitdistrplus,
  stats,
  dplyr
)
```

```{r}
# functions
# 1
data_group <- function(data,before, after){
  data$BA <- NA
  data$group <- NA
  ib <- before
  ia <- after
  for (i in ib :dim(data)[1]){
  if(data$pub[i] == 1){
    data$BA[(i-ib):(i-1)] <- "Before"
    data$BA[i:(i+ia-1)] <- "After"
    data$group[(i-ib):(i+ia-1)] <-as_date(data$Date[i])
  }
  }
    return(data)
}

# 2
tag_data <- function(GSPC){
  GSPC$Date <- ymd(GSPC$Date)

  # tag weekdays
  GSPC$wday <- wday(GSPC$Date)

  # years and month
  GSPC$year <- year(GSPC$Date)
  GSPC$month <- month(GSPC$Date)
  GSPC$ym <- str_c(GSPC$year,GSPC$month,sep= "-")

  # publication date
  Nub <- 0
  GSPC$pub <- 0
  for (i in 2:dim(GSPC)[1]){
    ym <- GSPC$ym[(i-1)]
    if(GSPC$ym[i] == ym){
      if(GSPC$wday[i] == 6){
        Nub <- Nub+1
        GSPC$pub[i] <- Nub
      }
    }
    else{
      ym <- GSPC$ym[i]
      Nub <- 0
      if(GSPC$ym[i] == ym){
        if(GSPC$wday[i] == 6){
          Nub <- Nub+1
          GSPC$pub[i] <- Nub
        }
      }
    }
  }

  for (i in 1:dim(GSPC)[1]){
    if(GSPC$pub[i] != 1){
      GSPC$pub[i] <-0
    }
  }
    return(GSPC)  
}

# 3
select_data <- function(GSPC){
  GSPC <- GSPC %>% dplyr::select("Date","Close","ym","pub","pct","VixStatus")
  return(GSPC)
}
```

## Data clean & EDA

# Read data

```{r}
#Dataframe setup
today <- Sys.Date()
sp500 <- new.env()
vix <- new.env()

invisible(
getSymbols("^GSPC",env = sp500, src = "yahoo",
           from = as.Date("1990-01-01"), to = as.Date(today),"getSymbols.warning4.0"=FALSE)
)

invisible(
getSymbols("^VIX",env = vix, src = "yahoo",
           from = as.Date("1990-01-01"), to = as.Date(today)))

GSPC <- sp500$GSPC
GSPC <- tibble(date=index(GSPC),coredata(GSPC$GSPC.Close))

names(GSPC)[names(GSPC) == "coredata(GSPC$GSPC.Close)"] <- "Close"
names(GSPC)[names(GSPC) == "date"] <- "Date"

VIX <- vix$VIX
VIX <- tibble(date=as.Date(index(VIX)),coredata(VIX$VIX.Close))

names(VIX)[names(VIX) == "coredata(VIX$VIX.Close)"] <- "Close"
names(VIX)[names(VIX) == "date"] <- "Date"

VIX$VixStatus <- 
  ifelse(VIX$Close >= 30, 4,
         ifelse(VIX$Close >= 20, 3,
                ifelse(VIX$Close >= 12, 2, 1)))
VIX$VixStatus <- ordered(VIX$VixStatus, labels = c('Low','Med','High', 'EXT High'))
# percentage
GSPC$pct <- NA
for (i in 2:dim(GSPC)[1]){
  GSPC$pct[i] <- ((GSPC$Close[i] - GSPC$Close[(i-1)])/GSPC$Close[(i-1)])*100
}
GSPC <- as.data.frame(GSPC)

VIX <- VIX %>% as.data.frame() %>% dplyr::select("Date","VixStatus") 
```

# Tag publication date
```{r}
GSPC <- left_join(GSPC, VIX, by = "Date", copy = F)
GSPC <- tag_data(GSPC)

```

# Select a smaller data frame
```{r}
GSPC <- select_data(GSPC)
```

# 5 days before & 1 day after
```{r}
GSPC <- data_group(GSPC,4,1)
# GSPC <- data_group(GSPC,5,1)
```

# Delete NA
```{r}
dt <- na.omit(GSPC)
```

# VixStatus
```{r}
# For VixStatus of low, med, high, ext
# dt <- filter(dt, VixStatus == "Low")
# dt <- filter(dt, VixStatus == "Med")
# dt <- filter(dt, VixStatus %in% c("Med","High","EXT High"))
# dt <- filter(dt, VixStatus == "High")
dt <- filter(dt, VixStatus == "EXT High")
```

# Compare before and after
```{r}
before <- dt %>% filter(BA == "Before")
after <- dt %>% filter(BA == "After")
BA <- c("Before","After")
mean <- c(mean(before$pct), mean(after$pct))
mean <- data.frame(BA, mean)
```

# Histgrams
```{r}
P_BA <- ggplot(data = dt, aes(x = pct)) + 
  geom_density(alpha=.2, aes(fill=BA)) +
  geom_vline(data = mean, aes(xintercept = mean, colour = BA), linetype = "dashed") +
  labs(title = "Distribution under Low Vix", x = "Percentage Change of Closed Price", y = "Density")
# + 
  # facet_grid(~ VixStatus)
P_BA

P_VIX <- ggplot() + geom_density(data = dt, aes(x = pct, colour = BA)) +
  labs(title = "Distribution under Different Vix Conditions", x = "Percentage Change of Closed Price", y = "Density") +
  facet_grid(~ VixStatus) 
  
P_VIX
```

# use chi-square test and K-S test
```{r}
# summary(after$pct>0)
# summary(before$pct>0)
test <- matrix(c(sum(before$pct>0),sum(after$pct>0),sum(before$pct<=0),sum(after$pct<=0)),ncol = 2, nrow = 2)
# kableExtra::kable(test)
chisq.test(test)

ks.test(after$pct, before$pct)
B <- ks.test(after$pct, before$pct)
B <- as.data.frame(unlist(B))
kableExtra::kable(B)
```


# Fit disttrition
```{r}
distBe <- fitdist(before$pct, "norm", method = "mle")
summary(distBe)
plot(distBe)

distAf <- fitdist(after$pct, "norm", method = "mle")
summary(distAf)
plot(distAf)
```

# Normal test and t test (not use)
```{r eval=FALSE, include=FALSE}
# qqnorm(bb,col="cadetblue3",main = "Before");qqline(bb,col="red")
# 
# qqnorm(aa,col="cadetblue3",main = "after");qqline(aa,col="red")
# 
# fortest <- melt(Diff, id = "group" )
# names(fortest)[names(fortest) == "variable"] <- "BA"
# names(fortest)[names(fortest) == "value"] <- "pct"
# fortest$BA <- as.factor(fortest$BA)
# 
# # t_test for before and after group
# # qqPlot(lm(log(High)~Student, data = email), simulate = TRUE, main = 'QQ Plot', labels = FALSE)
# t_test <- t.test(pct~BA, fortest, paired = FALSE, alternative = 'two.sided')
# t_test
```



# Dataframe (not use)
```{r eval=FALSE, include=FALSE}
before <- before %>% group_by(group) %>% summarise(mean_pct = mean(pct))
after <- after %>% group_by(group) %>% summarise(mean_pct = mean(pct))

names(before)[names(before) == "mean_pct"] <- "Before"
names(after)[names(after) == "mean_pct"] <- "After"

Diff <- left_join(before, after, by = "group")
```

# Percentages difference (not use)
```{r eval=FALSE, include=FALSE}
Diff$Difference <- Diff$After - Diff$Before
Diff$group <- as_date(Diff$group)
Diff$P_N <- NA
for (i in 1:dim(Diff)[1]){
  if(Diff$Difference[i] > 0){ 
    Diff$P_N[i] <- "Positive"
  }
  else{
    Diff$P_N[i] <- "Negative"
  }
}
# hist(Diff$Difference,breaks = 50)
ggplot(Diff, aes(x = group, y = Difference, fill = P_N)) + geom_bar(stat = "identity") +
  labs(x = "Time", y = "After - Before")
  
# qqnorm(Diff$Difference,col="cadetblue3",main = "Before");qqline(bb,col="red")
```

# Dataframe (not use)
```{r eval=FALSE, include=FALSE}
# before <- before %>% group_by(group) %>% summarise(mean_pct = mean(pct))
# after <- after %>% group_by(group) %>% summarise(mean_pct = mean(pct))
# 
# names(before)[names(before) == "mean_pct"] <- "Before"
# names(after)[names(after) == "mean_pct"] <- "After"
# 
# Diff <- left_join(before, after, by = "group")

```

# Normal test and t test (not use)
```{r eval=FALSE, include=FALSE}
# qqnorm(bb,col="cadetblue3",main = "Before");qqline(bb,col="red")
# 
# qqnorm(aa,col="cadetblue3",main = "after");qqline(aa,col="red")
# 
# fortest <- melt(Diff, id = "group" )
# names(fortest)[names(fortest) == "variable"] <- "BA"
# names(fortest)[names(fortest) == "value"] <- "pct"
# fortest$BA <- as.factor(fortest$BA)
# 
# # t_test for before and after group
# # qqPlot(lm(log(High)~Student, data = email), simulate = TRUE, main = 'QQ Plot', labels = FALSE)
# t_test <- t.test(pct~BA, fortest, paired = FALSE, alternative = 'two.sided')
# t_test

```


# Percentages difference (not use)
```{r eval=FALSE, include=FALSE}
# Diff$Difference <- Diff$After - Diff$Before
# hist(Diff$Difference,breaks = 50)
# ggplot(Diff, aes(x = Difference)) + geom_density(colour = "cadetblue3")
# qqnorm(Diff$Difference,col="cadetblue3",main = "Before");qqline(bb,col="red")
```
